!                  **************************
                   MODULE DECLARATIONS_RICE2D
!                  **************************
!
!***********************************************************************
! RICE-2D   V7P2                                             02/11/2016
!***********************************************************************
!
!brief    DECLARATION OF PRINCIPAL RICE-2D VARIABLES
!
!history  F. HUANG (CLARKSON U.) AND S.E. BOURBAN (HRW)
!+        11/11/2016
!+        V7P3
!+        Coupling TELEMAC-2D with RICE-2D (ice modelling component)
!+        Initial developments
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF_DEF
!
!       NOTE: THIS MODULE IS ORGANIZED IN 6 PARTS
!
!       (1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (2) INTEGERS
!       (3) LOGICAL VALUES
!       (4) REALS
!       (5) STRINGS
!       (6) ALIASES (IF NECESSARY)
!
!
!-----------------------------------------------------------------------
!
!       0) INTEGERS, PARAMETER
!
!-----------------------------------------------------------------------
!
!     MAXIMUM NUMBER OF VALUES OF KEY-WORDS OF ONE KIND (INTEGER, LOGICAL, ETC.)
!
      INTEGER, PARAMETER :: MAXKEY = 300
!     GRAPHIC PRINTOUT PERIOD RICE2D
!
      INTEGER LEOPRD
!
!     LISTING PRINTOUT PERIOD RICE2D
!
      INTEGER LISPRD
!
!     MAXIMUM NUMBER OF OUTPUT VARIABLES
!
      INTEGER, PARAMETER :: MAXICEVAR = 50
!
!
!-----------------------------------------------------------------------
!
!       4) INTEGERS
!
!-----------------------------------------------------------------------
!
!     NUMBER OF DIFFERENTIATING ARRAYS, AND THOSE WITH A GIVEN NAME
!
!      INTEGER NICVAR,N_NAMES_ICVAR
!
!     ICE PROCESS
!
      INTEGER ICEPROCESS
!
!     NUMBER OF TRACERS ADDED WHEN USING WAQPROCESS
!
      INTEGER  ICETR
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
      LOGICAL SORLEO(MAXICEVAR),SORIMP(MAXICEVAR)
!
!     RICE2D RESULT FILE NUMBER
!
      INTEGER ICERES
!
!     RICE2D BOUNDARY CONDIITON FILE NUMBER
!
      INTEGER ICECLI
!
!     RICE2D GEOMETRY FILE NUMBER
!
      INTEGER ICEGEO
!
!     RICE2D HYDRODYNAMICS FILE NUMBER
!
      INTEGER ICEHYD
!
!     RICE2D STEERING FILE NUMBER
!
      INTEGER ICECAS
!
!     RICE2D REFERENCE FILE NUMBER
!
      INTEGER ICEREF
!
!     DEBUGGER
!
      INTEGER DEBUG
!
!-----------------------------------------------------------------------
!
!       1) VECTORS (REAL AND INTEGER)
!
!-----------------------------------------------------------------------
!
!     ICE CONCENTRATION AS COMPUTED FROM SURFACE ICE PARTICLES
!     (ALSO USED TO DEFINE WHETHER A NODE IS IN OPEN WATER
!      OR UNDER ICE COVER)
      TYPE(BIEF_OBJ), TARGET :: ANFEM
!
!     water surface gradient
!      TYPE(BIEF_OBJ), TARGET :: DETAX,DETAY
!
!     WATTER SURFACE ELEVATION
!      TYPE(BIEF_OBJ), TARGET :: ETA
!
!     ELEVATION OF THE BOTTOM OF ICE
!      TYPE(BIEF_OBJ), TARGET :: ETAB
!
!     THERMAL BUDGET: NET HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: SUMPH
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLEAR SKY
      TYPE(BIEF_OBJ), TARGET :: PHCL
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLOUDY SKY
      TYPE(BIEF_OBJ), TARGET :: PHRI
!
!     THERMAL BUDGET: NET SOLAR RADIATION AFTER REFLECTION
      TYPE(BIEF_OBJ), TARGET :: PHPS
!
!     THERMAL BUDGET: EFFECTIVE BACK RADIATION
      TYPE(BIEF_OBJ), TARGET :: PHIB
!
!     THERMAL BUDGET: EVAPORATION HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIE
!
!     THERMAL BUDGET: CONDUCTIVITY HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIH
!
!     THERMAL BUDGET: PRECIPITATION
      TYPE(BIEF_OBJ), TARGET :: PHIP
!
!     THERMAL BUDGET: HEAT TRANSFER BETWEEN WATER AND ICE
      TYPE(BIEF_OBJ), TARGET :: PHIWI
!
!     WATER DEPTH
!      TYPE(BIEF_OBJ), TARGET :: HTW
!
!     WATER TEMPERATURE
!      TYPE(BIEF_OBJ), TARGET :: FRAZIL
!
!     FRAZIL CONCENTRATION
      TYPE(BIEF_OBJ), TARGET :: CV_F
!
!     WATER TEMPERATURE
!      TYPE(BIEF_OBJ), TARGET :: TW
!
!     HEAT TRANSFER COEFFICIENT BETWEEN SURFACE ICE AND WATER
!      TYPE(BIEF_OBJ), TARGET :: HWIN
!      DOUBLE PRECISION HWIN
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - OPEN WATER
!      TYPE(BIEF_OBJ), TARGET :: THETA0
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - ICE
!      TYPE(BIEF_OBJ), TARGET :: THETA1
!
!     COEFFICIENT QUANTIFYING THE RATE OF REENTRAINMENT OF SURFACE
!       ICE PER UNIT AREA
!      TYPE(BIEF_OBJ), TARGET :: BETA1
!
!     COEFFICIENT QUANTIFYING THE RATE OF ACCRETION TO THE
!       BED PER UNIT AREA
!      TYPE(BIEF_OBJ), TARGET :: GAMC
!
!     COEFFICIENT QUANTIFYING THE RATE OF ACCRETION TO THE
!       BED PER UNIT AREA
!      TYPE(BIEF_OBJ), TARGET :: GAMA
!
!     AVERAGE RISING VELOCITY OF FRAZIL ICE IN THE TURBULENT RIVER FLOW
!      TYPE(BIEF_OBJ), TARGET :: VBB
!
! ICE PROPERTY ON THE NODES/POINTS  ICE CONCENTRATION,THICKNESS,VELOCITY
!      TYPE(BIEF_OBJ), TARGET :: DTHIFEM
!
!      TOTAL WATER DISCHARGE
!      TYPE(BIEF_OBJ), TARGET :: QX,QY
!
!      ICE VELOCITY
!      TYPE(BIEF_OBJ), TARGET :: UICE,VICE,ZICE
!
!      DISCHARGE IN THE ICE LAYER
!      TYPE(BIEF_OBJ), TARGET :: UQX,UQY
!
!      WATER VELOCITY MAGNITUDE
!      TYPE(BIEF_OBJ), TARGET :: ZWAT
!
!      RELATIVE VELOCITY BETWEEN ICE - WATER
!      TYPE(BIEF_OBJ), TARGET :: ZWI
!
!      TYPE(BIEF_OBJ), TARGET :: TMICE,CNIEND
!
!     BED AND ICE INFLUENCING DEPTH
!      TYPE(BIEF_OBJ), TARGET :: HBED,HICE
!
!     SOLID ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIFEMS
!
!     FRAZIL ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIFEMF
!
!     ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIFEM
!
!     ICE SHEAR STRESS ON THE FLOW
!      TYPE(BIEF_OBJ), TARGET :: TIWX,TIWY
!
!     UNDERCOVER ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: HUN
!
!     ANCHOR ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THUN
!
!     CRUST ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: TISFEM
!
!     MASS OF SOLID AND FRAZIL LAYER, RESPECTIVELY
!      TYPE(BIEF_OBJ), TARGET :: PMS,PMF
!
!     ICE PARCEL AREA
!      TYPE(BIEF_OBJ), TARGET :: AREAP
!
!     TOTAL ICE MASS
!      TYPE(BIEF_OBJ), TARGET :: PM
!
!     THICKNESS OF SOLID AND FRAZIL LAYER, RESPECTIVELY
!      TYPE(BIEF_OBJ), TARGET :: THIPS,THIPF
!
!     INITIAL ICE THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THI0P
!
!     X,Y COORDINATE OF ICE PARCEL AT TN
!      TYPE(BIEF_OBJ), TARGET :: XP0,YP0
!
!     VELOCITY OF ICE PARCEL AT TN
!      TYPE(BIEF_OBJ), TARGET :: UPX0,UPY0
!
!     X,Y COORDINATE OF ICE PARCEL AT TN+1
!      TYPE(BIEF_OBJ), TARGET :: XP,YP
!
!     VELOCITY OF ICE PARCEL AT TN + 1
!      TYPE(BIEF_OBJ), TARGET :: UPX,UPY
!
!     MASS DENSITY OF ICE PARCEL AT TN AND TN+1
!      TYPE(BIEF_OBJ), TARGET :: UM0,UM
!
!     WATER DEPTH UNDER THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: HHPK
!
!
!      TYPE(BIEF_OBJ), TARGET :: VIC
!
!     ICE PARCEL SIZE TN+1
!      TYPE(BIEF_OBJ), TARGET :: HPX,HPY
!
!     ICE PARCEL SIZE TN
!      TYPE(BIEF_OBJ), TARGET :: HPX0,HPY0
!
!     GRADIENT TERMS
!      TYPE(BIEF_OBJ), TARGET :: DUDX,DUDY,DVDX,DVDY,DUDXT,
!     &                          DUDYT,DVDXT,DVDYT
!
!     INTERNAL STRESS
!      TYPE(BIEF_OBJ), TARGET :: SIGXX,SIGYY,SIGXY
!
!     PRESSURE
!      TYPE(BIEF_OBJ), TARGET :: PR
!
!     INTERNAL STRESS
!      TYPE(BIEF_OBJ), TARGET :: STRFX,STRFY
!
!     TIME STEP FOR ICE DYNAMICS
!      TYPE(BIEF_OBJ), TARGET :: TP,TPG
!
!     ICE PARCEL CONCENTRATION
!      TYPE(BIEF_OBJ), TARGET :: ANP
!
!     ICE PARCEL THICKNESS
!      TYPE(BIEF_OBJ), TARGET :: THIP
!
!     THE BOTTOM ELEVATION OF THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: BOTTOM_P
!
!     WATER SURFACE ELEVATION OF THE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: ETA_P
!
!     WATER VELOCITY UNDER THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: UPXW,UPYW
!
!     BOUNDARY ICE CONCENTRATION
!      TYPE(BIEF_OBJ), TARGET :: ANB
!
!     X,Y COORDINATE TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: XBFLX,YBFLX
!
!     ICE CONCENTRATION  AT THE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: ANFLX
!
!     DISTANCE TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: DLFLX
!
!     TIME TO ISSUE THE ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: TR
!
!     DIRECTION OF THE ICE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: SLPB
!
!     WATER VELOCITY AT THE ICE BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: VWXFLX,VWYFLX
!
!     DIRECTION OF THE SOLID BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: PAPHA1,PAPHA2
!
!     DISTANCE BETWEEN ICE PARCEL AND SOLID BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: PARDIS
!
!     DIRECTION OF THE ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PAPHABM1,PAPHABM2
!
!     DISTANCE BETWEEN ICE APARCEL AND ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PARDISBM
!
!     DIRECTION OF THE ICE BOOM (SIN,COS)
!      TYPE(BIEF_OBJ), TARGET :: ALPHA11,ALPHA12
!
!     DISTANCE BETWEEN ICE PARCEL AND ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: PARDS1
!
!     STRESS STATE
!      TYPE(BIEF_OBJ), TARGET :: KSTRSTATE
!
!     GRADIENT
!      TYPE(BIEF_OBJ), TARGET :: DUDYDVDXT
!
!     HYDROSTATIC PRESSURE
!      TYPE(BIEF_OBJ), TARGET :: HYDROPR
!
!     KERNEL
!      TYPE(BIEF_OBJ), TARGET :: PW
!
!     KERNEL DERIVATIVE
!      TYPE(BIEF_OBJ), TARGET :: PDWX,PDWY
!
!     ARTIFICIAL VISCOSITY
!      TYPE(BIEF_OBJ), TARGET :: AVISC
!
!     ICE BOOM COORDINATE
!      TYPE(BIEF_OBJ), TARGET :: XBM,YBM
!
!     ICE BOOM SPAN COORDINATE
!      TYPE(BIEF_OBJ), TARGET :: XBMSPAN,YBMSPAN
!
!     FORCE PER UNIT LENGTH IN SPAN J
!      TYPE(BIEF_OBJ), TARGET :: ASIGNP
!
!     ICE BOOM FLOAT OR SUBMERGE
!      TYPE(BIEF_OBJ), TARGET :: FRNUM1
!
!     ICE THICKNESS AT THE ICE BOOM J
!      TYPE(BIEF_OBJ), TARGET :: THISPAN
!
!     CRITICAL SUBMERGENCE LINE LOAD OF BOOM
!      TYPE(BIEF_OBJ), TARGET :: BMLINELD
!
!     CRITICAL ICE THICKNESS ABOVE SUBMERGED BOOM FOR RE-EMERGENCE
!      TYPE(BIEF_OBJ), TARGET :: THIEMERG
!
!     BOTTOM ELEVATION OF THE GATE
!      TYPE(BIEF_OBJ), TARGET :: GATE
!
!     BUOYANT FORCE OF THE ICE BOOM WHEN IT IS SUBMERGED
!      TYPE(BIEF_OBJ), TARGET :: BMBUOY
!
!     FRICTION COEFFICIENT BETWEEN THE ICE BOOM AND THE BOTTOM OF THE ICE
!      TYPE(BIEF_OBJ), TARGET :: BMFRIC
!
!
!
!
!-----------------------------------------------------------------------
!
!       2) INTEGERS
!     ICE ISLAND INDEX
!      TYPE(BIEF_OBJ), TARGET :: JAMFEM
!
!     BORDER ICE INDEX
!      TYPE(BIEF_OBJ), TARGET :: ISBORDER
!
!     ICE TYPE INDEX
!      TYPE(BIEF_OBJ), TARGET :: ICEREGION
!
!     ELEMENT NUMBER OF PARCEL LOCATION AT TN AND TN+1
!      TYPE(BIEF_OBJ), TARGET :: NPARELM,NPARELM0
!
!     BOUNDARY TYPE FOR ICE PARCEL
!      TYPE(BIEF_OBJ), TARGET :: NPOUT
!
!     ICE STOPPAGE
!      TYPE(BIEF_OBJ), TARGET :: IDELTA
!
!     NUMBER OF NEIGHBORING ICE PARCELS
!      TYPE(BIEF_OBJ), TARGET :: NXTP
!
!     TYPE(BIEF_OBJ), TARGET :: IDV
!
!     PARCEL'S NUMBER IN THE IMAGE PARCEL LIST
!      TYPE(BIEF_OBJ), TARGET :: NAPHA
!
!      TOTAL NUMBER OF NEIGHBORING ICE PARCELS
!      TYPE(BIEF_OBJ), TARGET :: INTN
!
!     PARCEL'S NUMBER OF BOOM IMAGE
!      TYPE(BIEF_OBJ), TARGET :: NAPHABM
!
!     TYPE OF ICE BOOM PARCEL IMAGE
!      TYPE(BIEF_OBJ), TARGET :: IPBOOM
!
!     SPAN OF THE ICE BOOM
!      TYPE(BIEF_OBJ), TARGET :: JSPAN
!
!     STARTING AND ENDING POINTS OF THE ICE FLUX BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: KPBD,KPBD1
!
!     THE NODE NUMBERS OF EACH ICE FLUX BOUNDARY
!      TYPE(BIEF_OBJ), TARGET :: NPBD
!
!     NUMBER OF ICE BOOMS
!      TYPE(BIEF_OBJ), TARGET :: NBM
!
!     NUMBER OF ICE BOOM SPANS
!      TYPE(BIEF_OBJ), TARGET :: NBMSPAN
!
!     ICE BOOM TYPES
!      TYPE(BIEF_OBJ), TARGET :: BOOMTYPE
!
!-----------------------------------------------------------------------
!
!
!-----------------------------------------------------------------------
!
!     NUMBER OF FRAZIL INPUT BOUNDARY
!
!      INTEGER NTWBC
!
!     # IWEATHER (=1, COMPLETE WEATHER DATA; =0, AIR TEMPERATURE ONLY))
!
      INTEGER IWEATYPE
!
!
!      INTEGER IND_F
!
!
!      INTEGER NBM
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
!
!     LOGICAL UNIT OF THE ICE RESULT FILE
!
!      INTEGER ICERES
!
!     LOGICAL UNIT OF THE ICE BOUNDARY CONDITION FILE
!
!      INTEGER ICECLI
!
!     LOGICAL UNIT OF THE GEOMETRY FILE
!
!      INTEGER ICEGEO
!
!     LOGICAL UNIT OF THE HYDRODYNAMIC FILE
!
!      INTEGER ICEHYD
!
!     LOGICAL UNIT OF THE ICE STEERING FILE
!
!      INTEGER ICECAS
!
!     LOGICAL UNIT OF THE ICE REFERENCE FILE
!
!      INTEGER ICEREF
!
!      INTEGER NNOD,NTBN,NHBN,NQBN,N0BN,NHTN,NFBN,NQB1,NQ0,NQ01,
!     &  NEL,NLB,NOB,NSBN
!
!     NUMBER OF PARCEL IN THE DOMAIN
!      INTEGER   NPARIN
!
!     NUMBER OF PARCEL MOVING OUT OF THE DOMAIN
!      INTEGER NPAROUT
!
!     DELETE THE BAD PARCELS
!      INTEGER NBADPARCELS
!      INTEGER KPRT
!      INTEGER KDMPH
!      INTEGER KDMPI
!      INTEGER KDMPHI
!      INTEGER KFLXI
!      INTEGER KWND
!      INTEGER KELV,KFLX,
!     &  KHDW,KHDI,KHOT,KSTR,KTHR,IRND,ITHIUP,ITHIMAX,ISEED
!          ! UPDATE BOUNDARY AND OUTPUT
!     & JOBFLX,NSEC,NDISC,NELEV,ISTRT,ITBDF,
!     & IHDW0,IHDW,IHOT0,IHOT,ISTR0,ISTR,IPRO,IPLT
!
!
!
!
!-----------------------------------------------------------------------
!
!       3) LOGICAL
!
!-----------------------------------------------------------------------
!      LOGICAL ICEDYNAMICS
!
!     ITHERMOSWITCH:
!        = 0, NO THERMAL CALCULATION
!        = 1, WITH THERMAL CALCULATION
!      LOGICAL ITHERMOSWITCH
!
!     IUNDERCOVERTRANSPORTSWITCH:
!        = 0, NO UNDER COVER TRANSPORT CALCULATION
!        = 1, WITH UNDERCOVER TRANSPORT CALCULATION
!      LOGICAL IUNDERCOVERTRANSPORTSWITCH
!
!     IBREAKUPSWITCH
!        = 0, NO BREAKUP CALCULATION
!        = 1, WITH BREAKUP CALCULATION
!      LOGICAL IBREAKUPSWITCH
!
!     IF YES, MASS-BALANCE
!      LOGICAL ICEBILMAS
!
!     IF YES, VALIDATION
!      LOGICAL ICEVALID
!
!     STEADY HYDRODYNAMICS
!      LOGICAL  PERMA
!
!     IF TEMPERATURE IS VARIABLE
!      LOGICAL YATEMP
!
!-----------------------------------------------------------------------
!
!       4) REALS
!
!-----------------------------------------------------------------------

!      DOUBLE PRECISION RHOW,RHOICE,RHOAIR,ROI
!     ICE LATENT HEAT
      DOUBLE PRECISION XLATEN
!
!     CLOUDINESS
      DOUBLE PRECISION CC
!
!     GEOGRAPHIC LATITUDE, + FOR NORTH, - FOR SOUTH
      DOUBLE PRECISION PHID
!
!     HEIGHT THE WIND DATA IS MEASUR ED(M)
      DOUBLE PRECISION Z1
!
!     ELEVATION MEASURED FROM SEA  LEVEL(M)
      DOUBLE PRECISION ZH
!
!     SUN EXIT ANGLE, 180 FOR HO RIZONTAL
      DOUBLE PRECISION ALPHSD
!
!     SUN EMISION ANGLE, 0 DEGRE E FOR HORIZONTAL
      DOUBLE PRECISION ALPHRD
!
!     SOLAR CONSTANT (W/M^2)
      DOUBLE PRECISION SIO
!
!     STANDARD LONGITUDE, IN DEG REES
      DOUBLE PRECISION ALSM
!
!     LOCAL LONGITUDE, IN  DEGREES
      DOUBLE PRECISION ALLM
!
!     -1, FOR WEST LONGITUDE; + FOR EAST LONGITUDE
      DOUBLE PRECISION ETADIR
!
!     ALBEDO OF ICE
      DOUBLE PRECISION ALBE
!
!--------------------------------------------------------------
!  GROUP FOR SIMULATING WATER TEMPERATURE AND THERMAL GROWTH AND DECAY OF ICE
!
!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION HWA
!
!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION HIA
!
!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION ALP
!
!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION ALPW
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR TURBULENT FLOW
      DOUBLE PRECISION CWI1
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR SUPERCOOLED TURBULENT FLOW
      DOUBLE PRECISION CIW1
!
!     NUSSELT NUMBER FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR LAMINAR FLOW
      DOUBLE PRECISION ATA
!
!     THERMAL CONDUCTIVITY OF BLACK ICE (W/M/OC)
!      DOUBLE PRECISION XKI
!
!     THERMAL CONDUCTIVITY OF WHITE ICE(W/M/OC)
!      DOUBLE PRECISION XKW
!
!     THERMAL CONDUCTIVITY OF SNOW(W/M/OC)
!      DOUBLE PRECISION XKS
!
!     HEAT TRANSFER COEFFICIENT FROM WATER TO ICE
!      DOUBLE PRECISION CWI
!
!------------------------------------------------------------------------
!   GROUP FOR SIMULATING BORDER ICE FORMATION
!
!     CRITICAL WATER SURFACE TEMPERATURE FOR BORDER ICE FORMATION
!      DOUBLE PRECISION TC
!
!     CRITICAL VELOCITY ABOVE WHICH SKIM ICE WILL NOT FORM (M/S)
!      DOUBLE PRECISION VCRSKM
!
!     SHORE ICE ACCUMULATION DOES NOT OCCUR WHEN AVERAGE FLOW VELOCITY EXCEED THIS VALUE(M/S)
!      DOUBLE PRECISION VCRBOM
!
!     MAXIMUM CONCENTRATION FOR BORDER ICE FORMATION
!      DOUBLE PRECISION ANMAXBORDER
!
!----------------------------------------------------------------------------
! GROUP FOR SKIM ICE SIMULATION
!
!     INITIAL SKIM ICE THICKNESS(M)
!      DOUBLE PRECISION HI0
!
!     MAXIMUM CONCENTRATION FOR SKIM ICE RUN
!      DOUBLE PRECISION ANMAXSKIM
!
!--------------------------------------------------------------------------
! GROUP FOR MASS EXCHANGE BETWEEN SUSPENDED LAYER, SURFACE LAYER AND ANCHOR ICE
!
!     INITIAL THICKNESS OF FRAZIL PART OF ICE FLOES(M)
!      DOUBLE PRECISION HF0
!
!     MAXIMUM CONCENTRATION OF FRAZIL ICE PARCEL FROM SUSPENDED LAYER TO SURFACE LAYER
!      DOUBLE PRECISION ANMAXFRA
!
!     MINIMUM CONCENTRATION OF FRAZIL ICE PARCEL FROM SUSPENDED LAYER TO SURFACE LAYER
!      DOUBLE PRECISION ANMINFRA
!
!     POROSITY OF FRAZIL ICE
!      DOUBLE PRECISION EF
!
!-----------------------------------------------------------------------------------
! GROUP FOR SUPERCOOLING SIMULATION
!
!     NUSSELT NUMBER
!      DOUBLE PRECISION VNU
!
!     LENGTH OF A-AXIS OF A FRAZIL CRYSTAL(M)
!      DOUBLE PRECISION DF
!
!     FRAZIL CRYSTAL THICKNESS(M)
!      DOUBLE PRECISION DE
!
!     NUCLEATION TEMPERATURE(OC)
!      DOUBLE PRECISION TUN
!
!     INITIAL SURFACE ICE CONCENTRATION
!      DOUBLE PRECISION CA0
!
!     INITIAL SUSPENDED FRAZIL CONCENTRATION
!      DOUBLE PRECISION CV0
!
!     THERMAL CONDUCTIVITY OF WATER (W/M/OC)
      DOUBLE PRECISION XKWP
!
!     FREEZING POINT OF WATER
      DOUBLE PRECISION TMELT
!
!     DISPERSION LONGITUDINALE,TRANSVERSALE
!      DOUBLE PRECISION LDISP,TDISP
!-------------------------------------------------------------------------------
!  GROUP FOR UNDERCOVER TRANSPORT SIMULATION
!
!     NOMINAL DIAMETER OF ICE PARTICLES(M)
!      DOUBLE PRECISION UNPSIZE
!
!     CRITICAL FLOW STRENGTH, BELOW WHICH THERE IS NO ICE TRANSPORT
!      DOUBLE PRECISION UNTHETAC
!
!     MAXIMUM CONCENTRATION OF UNDERCOVER LOAD
!      DOUBLE PRECISION UNMAXANP
!
!     THE RATIO OF UNCOVER LOAD TRANSPORTATION VELOCITY TO FLOW VELOCITY
!      DOUBLE PRECISION UNALPHAV
!
!-------------------------------------------------------------------------------
!  GROUP FOR ICE COVER FORMATION
!
!     ICE PARCEL STOPPAGE CRITERION
!      DOUBLE PRECISION STPV
!
!     CRITICAL FROUDE NUMBER FOR ICE PARCEL TO SUBMERGE
!      DOUBLE PRECISION CRIFR
!
!     EROSION VELOCITY OF ICE PARCELS
!      DOUBLE PRECISION UEROS
!
!     CRITICAL VELOCITY FOR FREEZING CALCULATION
!      DOUBLE PRECISION VCRFRZ
!
!     COMPRESSIVE STRENGTH OF THE ICE COVER
!      DOUBLE PRECISION STRENGTH
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
!      DOUBLE PRECISION WFV0,WFV1
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
!      DOUBLE PRECISION WFT0,WFT1
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
!      DOUBLE PRECISION WFV0DW,WFV1DW
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
!      DOUBLE PRECISION WFT0DW,WFT1DW
!
!
!      DOUBLE PRECISION TIME,GRAVT,CORIO,PI,SQPI,
!     &  RHO,RHOI,RADDIG,RHOS
!
! PARAMETERS FOR ICE
!     SUB-GRID SIZE
!      DOUBLE PRECISION SGRD
!
!     INITIAL ICE PARCEL CONCENTRATION
!      DOUBLE PRECISION AN0
!
!     INITIAL ICE THICKNESS
!      DOUBLE PRECISION THI0
!
!     INITIAL SIZE OF ICE PARCEL
!      DOUBLE PRECISION HPI0
!
!     MAXIMUM ICE CONCENTRATION
!      DOUBLE PRECISION ANMAX
!
!     ICE TIME STEP
!      DOUBLE PRECISION TIMICE
!
!     A MINIMUM VALUE
!      DOUBLE PRECISION VSM
!
!     NUMBER OF ICE PARCELS
!      DOUBLE PRECISION KNP
!
!     ICE PARCEL MASS
!      DOUBLE PRECISION PM1
!
!      DOUBLE PRECISION ANGLE   ! MAY NOT NEED;   WIND ANGLE
!
!      DOUBLE PRECISION REFEL   ! MAY NOT NEED; REFERENCE LEVEL FOR HYDRO
!
!      DOUBLE PRECISION OPTIM  ! MAY NOT NEED; OPTIMAL TIME STEP FOR HYDRO
!
!     DARCY'S COEFFICIENT FOR SEEPAGE FLOW IN RUBBLE ICE
!      DOUBLE PRECISION DARCYRUB
!
!     DARCY'S COEFFICIENT FOR SEEPAGE FLOW IN ICE ISLANDS
!      DOUBLE PRECISION  DARCYILD
!
!     MANNING's N OF ICE ISLANDS OR BORDER ICE
!
!      DOUBLE PRECISION CNISLD
!
!     ICE MASS DENSITY AND ICE MASS AT TN
!      DOUBLE PRECISION UMI0,PMI0
!
!     FRICTION COEFFICIENT BETWEEN ICE-RIVERBANK; ICE-RIVERBED
!      DOUBLE PRECISION FRIC1,FRIC2
!
!     AIR-ICE DRAG COEFFICIENT
!      DOUBLE PRECISION CA
!
!     INITIAL ICE ROUGHNESS
!      DOUBLE PRECISION CNI
!
!     MAX ICE ROUGHNESS
!      DOUBLE PRECISION CNIMAX
!
!     ICE INTERNAL FRICTION ANGLE
!      DOUBLE PRECISION PHI
!
!     EMPIRICAL CONSTANT
!      DOUBLE PRECISION PJ
!
!     MAX WATER-ICE DRAG COEFFICIENT
!      DOUBLE PRECISION CWMAX
!
!     BOLTZMANN CONSTANT (WM-2K-4)
      DOUBLE PRECISION SGMA
!
!     SPECIFIC HEAT OF WATER
      DOUBLE PRECISION CP
!
!     SPECIFIC HEAT OF ICE
      DOUBLE PRECISION CI
!
!     KINEMATIC VISCOSITY OF WATER
      DOUBLE PRECISION XNU
!
!      TIME FOR ICE DYNAMICS
!       DOUBLE PRECISION DELTATH,DELTATI,TIMICE0
!       DOUBLE PRECISION TMN
!       DOUBLE PRECISION ENDTIME
!       DOUBLE PRECISION ITMAX
!
!      STARTING TIME OF ICE DYNAMICS
!       DOUBLE PRECISION TICEBG
!
! VARIABLES FOR BOUNDARY CONDITIONS AND NODAL INFORMATION FOR HYDRODYNAMICS
! MAY NOT BE NEEDED
!       DOUBLE PRECISION NQN,SINBN,COSBN,NTN,NET,NHN,NELV,HB,NFLX,
!     &  QB,STEMP,CTEMP,N0N,NNELEV,KLB,KLE,NODELB,KOB,KOE,NODEOB,
!     &  KDB,KDE,DISCH,DISCHU,KLO1,KLO2,NNDISC,DXC,DYC,ELVTIME,FLXTIME,
!     &  WNDTIME,PRTTIME,DMPTIMH,FLXITIM,DMPTIMI,NSN,ELVATLOC,
!     &  FAC,QBT,NFLXSC,QBTI,QWCOEF,QIN,XBGN,YBGN,XEND,YEND
!
!-----------
!--ARRAYS ADDED BY SU FOR PARCEL SEARCH
!      COMMON /ARRY2D1/ MEGRID(MINGDX:MAXGDX,MINGDY:MAXGDY)
!      COMMON /ARRY2D2/ NDGRID(MINGDX:MAXGDX,MINGDY:MAXGDY)
!      COMMON /LINKEND/ LINKED(10,MAXNOD)
!      COMMON /LANDE/ NECODE(MAXEL),NSTAR(MAXEL),NEND(MAXEL),
!     &  ELMHT(MAXEL),ALAFAE(MAXEL),ALAFAN(MAXNOD),NODEL(3,MAXEL)
!      COMMON /SORT/ NSORT(MAXPAR)
!----------------

!
!-----------------------------------------------------------------------
!
!       5) STRINGS
!
!-----------------------------------------------------------------------
!
!     TITLE OF STUDY
!
      CHARACTER(LEN=72) TITICECAS
!
!     COPY OF SUBMIT STRINGS IN THE DICTIONARY
!
      CHARACTER(LEN=144) SUBMIT(4,300)

!     MAXIMUM OF LOGICAL UNITS NUMBERS
!
      INTEGER, PARAMETER :: MAXLU_ICE = 14
!
!     BIEF_FILES STRUCTURES
!
      TYPE(BIEF_FILE) :: ICE_FILES(MAXLU_ICE)
!
!
!      CHARACTER(LEN=50) CASENAME,FNAME,GEOFILE,TIMFILE,PRTFILE,
!     &  PTMFILE,FLXFILE,ELVFILE,WNDFILE,DSCFILE,
!     &  HD0FILE,IQBFILE,HO0FILE,GTEFILE,
!     &  HOTFILE,ERRFILE,STATE,STRFILE,THRFILE,DELFILE,
!     &  ST0FILE,QNIFILE,QNWFILE,BMFFILE,DBMFILE,CLGFILE,
!     &  LELFILE,NBMFILE,PROFILE,TBCFILE,LINKEFILE,SWIFILE,MCRFILE,
!     &  WEAFILE,ICEVOLUMEFILE,BRKFILE,NETFILE,COVFILE,PARFILE,
!     &  CLGDWFILE,DSCLOC,ELVLOC,DSCILOC
!
!      INTEGER, PARAMETER :: MAX_ICE_FILE = 1000
!
!      TYPE(BIEF_FILE) :: PLTFILE(MAX_ICE_FILE)
!      CHARACTER(LEN=50) PLTFILE(MAX_ICE_FILE)
!      TYPE(BIEF_FILE) :: CASENAME,FNAME,TIMFILE,
!     &  FLXFILE,ELVFILE,DSCFILE,TBCFILE,
!     &  HD0FILE,HDWFILE(1000),HDIFILE(1000),DSCLOC(200),
!     &  ELVLOC(200),IQBFILE,HO0FILE,THRFILE,DELFILE,CLGFILE,
!     &  HOTFILE(1000),ERRFILE,STATE(0:1),STRFILE(1000),
!     &  ST0FILE,QNIFILE,QNWFILE,BMFFILE,DSCILOC(200),
!     &  LELFILE,NBMFILE,PROFILE(1000),LINKEFILE,WEAFILE,
!     &  BRKFILE,SWIFILE,MCRFILE,PARFILE,
!     &  CLGDWFILE
!
!     NAMES OF ICE ARRAYS (GIVEN BY USER)
!
!      CHARACTER(LEN=32) NAMES_ICVAR(MAXVAR)
!
!-----------------------------------------------------------------------
!
!       5) BLOCKS
!
!-----------------------------------------------------------------------
!
!
!     BLOCK OF ICE VARIABLES
!
!      TYPE(BIEF_OBJ), TARGET :: ICVAR
!
!
      END MODULE DECLARATIONS_RICE2D
